### ISSUE TITLE
pushing to datahub.io

### ISSUE THREAD

**Issue by jalbertbowden** [scraperwiki/open-your-data#13]
was attempting to push .pdf scraped to datahub.io, getting this error:  
""Error{"readyState":0, "status":0,"statusText":"[Exception... \"<no message>\"  nsresult: \"0x805e0006 (<unknown>)\"  location: \"JS frame :: https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js :: .send :: line 2\"  data: no]"}"  
ff30beta
win7

**Comment by openjck** [comment]
This looks like a duplicate of #9

**Comment by StevenMaude** [comment]
Should be fixed by #16. (Although it will need deploying to the QuickCode servers at some point.)
