### ISSUE TITLE
Not possible to open general-interest data

### ISSUE THREAD

**Issue by openjck** [scraperwiki/open-your-data#14]
It's not possible to open general-interest data.

Data shared on *data.ckan.org* is deleted regularly, sharing data on *datahub.io* doesn't work as per #9, and the other data sharing service choices are meant for data relating to specific governments.

**Comment by frabcus** [comment]
I think the easiest way would be to get #9 fixed - we don't run a general purpose CKAN instance at ScraperWiki, and datahub.io would seem to be the right one to use!

**Comment by openjck** [comment]
I'm afraid this is still a problem. See [this comment](https://github.com/scraperwiki/open-your-data/issues/9#issuecomment-243010056).
