### ISSUE TITLE
Can't open my data to datahub.io

### ISSUE THREAD

**Issue by byrnedo** [scraperwiki/open-your-data#9]
When providing Dataset Title,  Dataset Name and License along with my api key with datahub.io selected  all I get is an error:
"readyState":0,"responseText":"","status":0,"statusText":"error"
I have an organisation set up on datahub.

**Comment by rossjones** [comment]
@morty This has worked previously, what's changed that means that this ONLY works with CKAN over HTTPS?

**Comment by drj11** [comment]
scraperwiki.com switched on HTTPS.

**Comment by rossjones** [comment]
And you make the call from JS rather than Python on the backend?

**Comment by drj11** [comment]
@rossjones yeah i think so. Of course, now you've asked that question it does seem that we could, in principle, do it from the backend server. That will require more reworking. But I think it is an option.

**Comment by openjck** [comment]
DataHub now supports HTTPS! :smile:

Unfortunately, I'm still seeing the issue described in [this comment](https://github.com/scraperwiki/open-your-data/issues/9#issuecomment-38699345). Does *Open Your Data* need to be updated to take advantage of DataHub's new HTTPS support?

**Comment by drj11** [comment]
Yes, the URL in the index.html page needs changing from http to https https://github.com/scraperwiki/open-your-data/blob/master/http/index.html#L29

**Comment by openjck** [comment]
Done :smile:

https://github.com/scraperwiki/open-your-data/pull/16

**Comment by openjck** [comment]
I'm afraid the suggested change didn't do the trick. The URL was changed from `http` to `https` but it's still not possible to push data to datahub.io. I get this error when trying:

> Error {"readyState":4,"responseText":"{\"help\": \"https://datahub.io/api/3/action/help_show?name=package_create\", \"success\": false, \"error\": {\"message\": \"Access denied: User openjck not authorized to create packages\", \"__type\": \"Authorization Error\"}}","status":403,"statusText":"Forbidden"}
